### ISSUE TITLE
Can I use lorawan in this?

### ISSUE THREAD

**Issue by tusharvb19** [armtronix/arduino-LoRa-STM32#1]
As this board comes with SX1276 and STM32 can I use this for LoRaWAN using lwic stack?
If yes can guide for it?
Thanks in advance.

**Comment by armtronix** [comment]
Plz refer this 
https://github.com/armtronix/arduino-lmic

**Comment by tusharvb19** [comment]
Thank you for your quick reply.
Also, can I make one of the STM32 Lora module to act as gateway using rpi or something else?

**Comment by armtronix** [comment]
Sorry we have never tried it.Our stm32 board can act as node ,code is available on the previously sent link

**Comment by tusharvb19** [comment]
Okay. But if I can use the SX1276 from the module externally to use with Rpi as guided here:
https://www.instructables.com/id/Use-Lora-Shield-and-RPi-to-Build-a-LoRaWAN-Gateway/
or
https://github.com/tftelkamp/single_chan_pkt_fwd
???

**Comment by armtronix** [comment]
Should be possible . Not tested . Probably some wire soldering may be required as the pins of lora module are not exposed

**Comment by tusharvb19** [comment]
I can test this but will need hardware details with respect to above links.
As the SPI pins will be shared by both rpi and stm32 and will try to place an empty sketch in stm32.
Thanks for the co-operation.

**Comment by tusharvb19** [comment]
Hello, Can I get hardware details for Bord 0.3 i.e. STM32 +LoRa?
Need to find SPI pins of LoRa Module.
Thanks in advance.

**Comment by armtronix** [comment]
Can you plz send an email on sales@armtronix.in
